### ISSUE TITLE
New releases are not available in maven repository

### ISSUE THREAD

**Issue by maokejackson** [GluuFederation/scim#65]
The latest stable version in https://ox.gluu.org/maven/ is 4.3.0.Final.
Where are version 4.3.1 and 4.4.1 hosted?

**Comment by Romeh** [comment]
same question guys ?

**Comment by nynymike** [comment]
Upstream SCIM project is moved to LF: https://github.com/JanssenProject/jans

**Comment by jgomer2001** [comment]
maven coordinates were updated long ago:

https://gluu.org/docs/gluu-server/4.4/user-management/scim2/#start-a-simple-project
