### ISSUE TITLE
chore: ensure the primary e-mail in the list is persisted to `mail` attribute

### ISSUE THREAD

**Issue by jgomer2001** [GluuFederation/scim#73]
Here https://github.com/GluuFederation/scim/blob/master/scim-rest/src/main/java/org/gluu/oxtrust/service/scim2/UserPersistenceHelper.java#L144

By convenience it is better to order the array so the primary e-mail is first, see ticket 11242

**Comment by mzico** [comment]
@jgomer2001 : which CE version has this fix? 4.5.1?

**Comment by jgomer2001** [comment]
@mzico 4.5.2
