### ISSUE TITLE
 https://maven.gluu.org/maven access to use scim client dependency  ? 

### ISSUE THREAD

**Issue by Romeh** [GluuFederation/scim#74]
Dears ,

I am trying to use SCIM client maven dependency but the maven repo is protected by user name and password , any public repo for the dependency ? 

```
<repositories>
  <repository>
    <id>gluu</id>
    <name>Gluu repository</name>
    <url>http://maven.gluu.org/maven</url>
  </repository>
</repositories>

<dependency>
  <groupId>org.gluu</groupId>
  <artifactId>scim-client</artifactId>
  <version>${scim.client.version}</version>
</dependency>
```

**Comment by jgomer2001** [comment]
@moabu @nynymike

**Comment by moabu** [comment]
Hey @Romeh ,

Sorry that you ran into that. Here is a comment about the change . 

https://github.com/GluuFederation/cloud-native-edition/issues/558#issuecomment-1598957412
